name: Run Spring Boot Selenium UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build and Run Tests with Maven
        run: mvn clean verify -Dspring.profiles.active=qa

      - name: Upload HTML Cucumber Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Cucumber HTML Report
          path: target/cucumber-advanced-reports/
